FROM java:8
COPY role-based-shop-management-discovery-server-0.0.1-SNAPSHOT.jar /
RUN bash -c 'touch /role-based-shop-management-discovery-server-0.0.1-SNAPSHOT.jar'
ENTRYPOINT ["java", "-jar", "/role-based-shop-management-discovery-server-0.0.1-SNAPSHOT.jar"]
